swagger: '2.0'
info:
  version: v1
  title: demoapi
  description: Demo purposes
  x-ibm-name: uniqueapp
host: $(catalog.host)
basePath: /demoapi
schemes:
  - https
produces:
  - application/json
paths:
  /v1/Customers:
    get:
      tags:
        - Customer
      description: Gets all Customers from the system that the user has access to
      operationId: getCustomer
      produces:
        - application/json
      x-swagger-router-controller: Customer
      responses:
        '200':
          description: Customer response
          schema:
            type: array
            items:
              $ref: '#/definitions/v1Customers'
        '404':
          description: Customer response
          schema:
            type: object
        '500':
          description: Customer response
          schema:
            type: object
      parameters:
        - name: filter
          in: query
          description: >-
            Filter defining fields, where, order, offset, and limit - must be a
            JSON-encoded string ({"something":"value"})
          type: string
    post:
      tags:
        - Customer
      description: Posts all Customers from the system that the user has access to
      operationId: postCustomer
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Customer
      responses:
        '204':
          description: Customer response
          schema:
            type: array
            items:
              $ref: '#/definitions/v1Customers'
        '404':
          description: Customer response
          schema:
            type: object
        '500':
          description: Customer response
          schema:
            type: object
      parameters:
        - name: v1/Customers
          in: body
          schema:
            $ref: '#/definitions/v1Customers'
    patch:
      tags:
        - Customer
      description: Patchs all Customers from the system that the user has access to
      operationId: patchCustomer
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Customer
      responses:
        '204':
          description: Customer response
          schema:
            type: array
            items:
              $ref: '#/definitions/v1Customers'
        '404':
          description: Customer response
          schema:
            type: object
        '500':
          description: Customer response
          schema:
            type: object
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  v1Customers:
    type: object
    properties:
      name:
        type: string
      address:
        type: object
        properties:
          city:
            type: string
        required:
          - city
    required:
      - name
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: 'https://uniqueapp.mybluemix.net$(request.path)$(request.search)'
          tls-profile: ''
          secure-gateway: false
    catch: []
